export const SET_PARKING_LOTS = 'SET_PARKING_LOTS';
export const PARKING_LOT_FETCHED = 'PARKING_LOT_FETCHED';
export const UPDATE_PARKING_LOT = 'UPDATE_PARKING_LOT';
export const DELETE_PARKING_LOT = 'DELETE_PARKING_LOT';