export const FETCHING_REQUEST = 'FETCHING_PARKING_LOT_REQUEST';
export const SET_ITEMS = 'SET_PARKING_LOTS';
export const ITEM_FETCHED = 'PARKING_LOT_FETCHED';
export const UPDATE_ITEM = 'UPDATE_PARKING_LOT';
export const DELETE_ITEM = 'DELETE_PARKING_LOT';

export const CHANGE_PARKING_LOT_STATUS = 'CHANGE_PARKING_LOT_STATUS';

export const ALLOCATED = 'allocated';
export const UNALLOCATED = 'unallocated';

export const STATUS = [ALLOCATED, UNALLOCATED]